version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - gabbloquet
  assignees:
  - gabbloquet
  versioning-strategy: increase
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.0
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 7.3.3
    - 7.3.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.4
    - 13.1.5
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
